### ISSUE TITLE
Problème de contraste

### ISSUE THREAD

**Issue by tsampy** [IFATech-Metz/dev-log-2#24]
La lecture de la météo est quasi-impossible : un fond d'écran quasi blanc avec une écriture blanche rend la lecture très difficile.
Le fond d'écran est choisi en fonction de la météo ?

**Comment by Niakette** [comment]
Oui le fond est généré en fonction de la météo, on va travailler dessus, on atends ton retour une fois que cela sera fait !

**Comment by Antopablo** [comment]
C'est modifié merci
